### ISSUE TITLE
Copying image not working

### ISSUE THREAD

**Issue by MuTsunTsai** [tomoyukim/vscode-mermaid-editor#81]
**Describe the bug**
When I tried to use the "Copy image" button, it only shows the following message in the output panel
```
[CaptureImageFailure]
undefined
```
without further info. This is not specific to particular diagram; I've tried many different diagrams but all failed.

**Screenshots**
![image](https://user-images.githubusercontent.com/39870664/233556973-c8dc479f-6f00-4cd0-9da2-e6155c8cabfd.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - VSCode version 1.77.3
 - Extension version 0.18.1

**Comment by daniecas** [comment]
I have the same scenario, the copy image button and copy image command doesn't work

**Comment by tomoyukim** [comment]
Thank you for reporting the bug. I found the cause. I will fix it in the next release. For short term, you can avoid the error by changing "MermaidEditor>Generate:Type" to `png` from the other value.

**Comment by daniecas** [comment]
Recently I updated my default browser and now it seems to work correctly, probably because the Diagram visualization is based on browser

**Comment by tomoyukim** [comment]
@daniecas I published v0.19.1 with this bug fix. Thank you for your reporting again.

**Comment by ianisms** [comment]
Issue still exists in 0.19.1:

OS: Windows 11
VSCode version 1.97.2
Extension version 0.19.1

Mermaid-editor > Generate: Type: png, jpg case the error:
[CaptureImageFailure]
undefined

SVG and webp are working
